# core service setup
core.id=ckpouch-front
core.name=CKPouch Front
core.version=0.5.0
#core.pipe=/home/appadmin/ckpouch/bdms-server/front/.fifo
#core.svcdir=/home/ckstack/apps/sea/service
core.svcdir=/home/ubuntu/apps/ckpouch/front/service
core.module-map=/conf/module-map.cfg.json
core.event-map=/conf/event-map.cfg.json
core.scheduler-map=/conf/scheduler-map.cfg.json
core.http-map=/conf/http-map.cfg.json
core.ws-map=/conf/ws-map.cfg.json
core.mqtt-map=/conf/mqtt-map.cfg.json
core.amqp-map=/conf/amqp-map.cfg.json
core.redis-map=/conf/redis-map.cfg.json

# log
log.console=true
log.out=/data/log/apps/ckpouch/front-out.log
log.err=/data/log/apps/ckpouch/front-err.log
log.max-files=14d
log.default-level=debug
log.scheduler-level=verbose
#log.mqtt.host=localhost
#log.mqtt.port=1883
#log.mqtt.username=ckpouch_user
#log.mqtt.password=ckpouch
#log.mqtt.protocol=mqtt
#log.mqtt.base-topic=sys/ckpouch/log
#log.mqtt.default-level=warn

# http setup
# usage : http.{alias}.{config}

http.core.port=10002
http.core.protocol=http

# # use for https 
# http.secure.port=10001
# http.secure.protocol=https
# http.secure.ssl.stg-bts\.auto-hmg\.io.ca=/data/cert/enabled/server.ca
# http.secure.ssl.stg-bts\.auto-hmg\.io.key=/data/cert/enabled/server.key
# http.secure.ssl.stg-bts\.auto-hmg\.io.passphrase=rwxk1g77


# ws setup
# usage : ws.{alias}.{config}
ws.core.port=10001
ws.core.protocol=ws

# # use for wss
# ws.secure.port=10002
# ws.secure.protocol=wss


# # mysql setup
# # usage : mysql.{alias}.{config}
# mysql.core.host=127.0.0.1
# mysql.core.port=13306
# mysql.core.username=ckpouch_user
# mysql.core.password=Tp=;SEPL+2aHWQt3
# mysql.core.max-conn-count=10
# mysql.core.db=ckpouch_core_db

# # redis setup
# # usage : redis.{alias}.{config}
# redis.core.host=127.0.0.1
# redis.core.port=6379
# redis.core.password=
# redis.core.db=6
# redis.core.psubscribe=[]
# redis.core.subscribe=[]

# redis.session.host=127.0.0.1
# redis.session.port=6379
# redis.session.password=
# redis.session.db=7
# redis.session.psubscribe=[]
# redis.session.subscribe=[]

# # mqtt setup
# # usage : mqtt.{alias}.{config}
# mqtt.core.host=localhost
# mqtt.core.port=1883
# mqtt.core.protocol=mqtt
# mqtt.core.username=ckpouch_user
# mqtt.core.password=ckpouch
# mqtt.core.client-id=ckpouch-user-:now
# mqtt.core.subscribe=[]
# mqtt.core.mode=ckpouch # ckpouch, plain available

# # amqp setup
# # usage : amqp.{alias}.{config}
# amqp.core.host=127.0.0.1
# amqp.core.port=5672
# amqp.core.queue=Q_UNPAID_CKPOUCH_FRONT
# amqp.core.queue-durable=true
# amqp.core.username=ckpouch_user
# amqp.core.password=ExCRXMch7GyvsLpt
# amqp.core.mode=ckpouch # ckpouch, plain available

# service setup
service.hello=world
# service api key
# http request header apiKey value should be [ckpouch-api-key]
service.api.key=ckpouch-api-key
# jwt setup
service.jwt.secret=ckpouch-secret-key
service.jwt.refresh-secret=ckpouch-refresh-secret-key
service.jwt.access-token-expiry-sec=3600
service.jwt.refresh-token-expiry=7d
# api server setup
service.api-server.protocol=http
service.api-server.host=localhost
service.api-server.port=11001

