# core service setup
core.id=ckpouch-front
core.name=CKPouch Front
core.version=0.5.0
core.pipe=/home/ckpush/ckpouch/bdms-server/front/.fifo
#core.svcdir=/home/ckstack/apps/sea/service
core.svcdir=/home/ckpush/ckpouch/bdms-server/front/service
core.module-map=/conf/module-map.cfg.json
core.event-map=/conf/event-map.cfg.json
core.scheduler-map=/conf/scheduler-map.cfg.json
core.http-map=/conf/http-map.cfg.json
core.ws-map=/conf/ws-map.cfg.json
core.mqtt-map=/conf/mqtt-map.cfg.json
core.amqp-map=/conf/amqp-map.cfg.json
core.redis-map=/conf/redis-map.cfg.json

# log
log.console=true
log.out=/data/log/apps/bdms-server/ckpouch-front-out.log
log.err=/data/log/apps/bdms-server/ckpouch-front-err.log
log.max-files=14d
log.default-level=debug
log.scheduler-level=verbose
#log.mqtt.host=localhost
#log.mqtt.port=1883
#log.mqtt.username=ckpouch_user
#log.mqtt.password=ckpouch
#log.mqtt.protocol=mqtt
#log.mqtt.base-topic=sys/ckpouch/log
#log.mqtt.default-level=warn

# http setup
# usage : http.{alias}.{config}
http.core.port=10002
http.core.protocol=https
http.core.ssl.dev10\.ckpush\.com.ca=/data/cert/enabled/server.ca
http.core.ssl.dev10\.ckpush\.com.key=/data/cert/enabled/server.key

# ws setup
# usage : ws.{alias}.{config}
ws.core.port=10002
ws.core.protocol=wss

# mysql setup
# usage : mysql.{alias}.{config}
mysql.core.host=localhost
mysql.core.port=3306
mysql.core.username=ckpouch_user
mysql.core.password=abcd1234!
mysql.core.max-conn-count=10
mysql.core.db=ckpouch_core_db

# redis setup
# usage : redis.{alias}.{config}
redis.core.host=localhost
redis.core.port=6379
redis.core.password=
redis.core.db=6
redis.core.psubscribe=[]
redis.core.subscribe=[]

redis.session.host=localhost
redis.session.port=6379
redis.session.password=
redis.session.db=7
redis.session.psubscribe=[]
redis.session.subscribe=[]

# mqtt setup
# usage : mqtt.{alias}.{config}
# mqtt.core.host=localhost
# mqtt.core.port=1883
# mqtt.core.protocol=mqtt
# mqtt.core.username=ckpouch_user
# mqtt.core.password=ckpouch
# mqtt.core.client-id=ckpouch-user-:now
# mqtt.core.subscribe=[]
# mqtt.core.mode=ckpouch # ckpouch, plain available

# amqp setup
# usage : amqp.{alias}.{config}
amqp.core.host=localhost
amqp.core.port=5672
amqp.core.queue=Q_UNPAID_CKPOUCH_FRONT
amqp.core.queue-durable=true
amqp.core.username=ckpouch
amqp.core.password=ckpouch.12
amqp.core.mode=ckpouch # ckpouch, plain available

# service setup
service.hello=world
service.auth.request-time-period=60
service.auth.signature-backdoor=c7c73c9a28684136b240ecc2364efc99
service.httpd-path=/home/ckpush/ckpouch/bdms-server/www
service.queue.producer=Q_CKPOUCH_SCRIPT
